packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/config/*'

catalog:
  '@nuxt/eslint': ^1.15.2
  '@nuxt/kit': ^4.3.1
  '@nuxtjs/i18n': ^10.2.3
  eslint: ^10.1.0
  nanoid: ^5.1.7
  nanoid-dictionary: ^5.0.0
  nuxt: ^4.3.1
  oxlint: ^1.51.0
  prettier: ^3.8.1
  typescript: ^5.9.3
  vue: ^3.5.29

minimumReleaseAge: 1440 # 24 hours
