import { readdir, writeFile } from 'node:fs/promises'
import { dirname, extname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const projectRoot = join(__dirname, '..')
const iconsDir = join(projectRoot, 'assets', 'icons')
const outputFile = join(projectRoot, 'utils', 'icon.ts')

const entries = await readdir(iconsDir, { withFileTypes: true })
const iconNames = entries
  .filter((entry) => entry.isFile() && extname(entry.name).toLowerCase() === '.svg')
  .map((entry) => entry.name.replace(/\.svg$/i, ''))
  .sort((a, b) => a.localeCompare(b))

const serialized = iconNames.map((name) => `  '${name}',`).join('\n')
const content = `// Auto-generated by scripts/generate-icons.mjs. Do not edit manually.
export const customIconList = [
${serialized}
] as const

export type CustomIconName = \`custom:\${(typeof customIconList)[number]}\`
`

await writeFile(outputFile, content)
console.log(`Generated ${outputFile} with ${iconNames.length} icons.`)
