services:
  drizzle-gateway:
    image: ghcr.io/drizzle-team/gateway:latest
    container_name: drizzle-gateway
    restart: always
    ports:
      - '4983:4983'
    environment:
      - PORT=4983
      - STORE_PATH=${DRIZZLE_GATEWAY_STORE_PATH:-./app}
      - MASTERPASS=${DRIZZLE_GATEWAY_MASTERPASS:-password}
    volumes:
      - drizzle_gateway_data:/app
